### ISSUE TITLE
java.lang.NoSuchMethodException: scripts.Script.main([Ljava.lang.String;)

### ISSUE THREAD

**Issue by raginjason** [jhole89/aws-glue-sbt-quickstart#2] opened 2020-09-23 00:24 UTC
I'm attempting to run this repo more or less as-is, to make things as simple as possible. I did my best to follow the directions provided. Here are some details about the state of things:

* OSX 10.15.6
* Changed project/build.properties to sbt.version = 1.3.13
* Commented out the ??? line in scripts/src/main/scala/scripts/Script.scala
* `aws s3 cp scripts/src/main/scala/scripts/Script.scala s3://<bucket>/admin/Script.scala`
* Ran `sbt sanity` without error
* `aws s3 cp shared/target/scala-2.11/myproj-shared-assembly-1.0.jar s3://<bucket>/admin/myproj-shared-assembly-1.0.jar` (note that this is slightly different from what the README says; it suggests `shared/target/*.jar`) 

Glue Settings:
* Glue version = `2.0`
* ETL language = `scala`
* Scala class name = `scripts.Script`
* Script location = `s3://<bucket>/admin/Script.scala`
* Jar lib path = `s3://<bucket>/admin/myproj-shared-assembly-1.0.jar`

When attempting to run this, in my logs I get a `java.lang.NoSuchMethodException: scripts.Script.main([Ljava.lang.String;)` and I'm not sure why. Any thoughts on this?

**Comment by jhole89** [comment] 2020-09-23 06:11
Hey @raginjason thanks for raising this and pointing out some discrepancies, i'll try and address them each:
* OSX 10.15.6 - I personally only use linux so can't reproduce this exactly, however I did previously run this on MacOS without issue.
* `shared/target/*.jar` vs `shared/target/scala-2.11/*.jar` - nice catch, you are 100% correct and I'll update the README.md
* sbt.version = 1.3.13 - I'll need to test this but can't do this right now
* Glue version = 2.0 - this is a new Glue release for AWS that only came out earlier this year, unfortunately I haven't had a chance to test this yet but will alongside the above sbt.version issue.
* ??? - I assume you replace it with some spark/glue code? Can you post it here (or send me a link if you don't wish for it to be public)?

The rest all seems sensible to me. One this that has popped to mind, is that `[Ljava.lang.String;` could be something to do with a an input stream (something that AFAIK was added in Glue 2.0), and given that the compilation was successful this leads me to think it maybe a breaking change in the line `Job.init(args("JOB_NAME"), glueCtx, args.asJava)` when using Glue 2.0.

I'll try and test my glue scripts with glue 2.0 to see if this replicates the issue but that may take me a day or two due to other prioritise. In the meantime I'd suggest trying to downgrade the job to Glue 1.0 and see if the same issue arises.

Thanks for taking the time to raise this - I'll try and automate some CI for new sbt and Glue releases so that these issues don't happen again.

**Comment by raginjason** [comment] 2020-09-23 14:43
For the actual job code, I just commented out the `???` placeholder. Here is the output of `git diff` of everything (very few changes):

```
diff --git a/project/build.properties b/project/build.properties
index 7609b47..cb6a5a8 100644
--- a/project/build.properties
+++ b/project/build.properties
@@ -1 +1 @@
-sbt.version = 1.2.8
\ No newline at end of file
+sbt.version = 1.3.13
diff --git a/scripts/src/main/scala/scripts/Script.scala b/scripts/src/main/scala/scripts/Script.scala
index 79a8fe9..95e49b4 100644
--- a/scripts/src/main/scala/scripts/Script.scala
+++ b/scripts/src/main/scala/scripts/Script.scala
@@ -7,6 +7,6 @@ object Script extends BaseGlueScript {

   // run is the entry point invoked
   override def run(myArg: String): Unit = {
-    ???
+    //???
   }
 }
```

I tested this with Glue 1.0; at first it did not work. After some iteration, passing in _Input arguments_ of `--myArg SomeValue` got it to execute without error. Trying these same _Input arguments_ in to the Glue 2.0 job did not result in any change unfortunately.

I believe you are correct about this being a Glue 2.0 issue. A cursory search in the changelog for Glue does not suggest anything that might impact this, but perhaps you'll have better luck than I

**Comment by jhole89** [comment] 2020-09-23 15:23
Thanks @raginjason can I also confirm whether you updated the `build.sbt` to use the AWSGlueLib 2.0.0?

**Comment by raginjason** [comment] 2020-09-23 16:58
That's the entire diff output, so no. I can try that and see what happens though

**Comment by jhole89** [comment] 2020-09-23 17:01
You would absolutely need to use the AWSGlue 2.0 lib in the build if you want to run it using AWSGlue 2.0.

**Comment by raginjason** [comment] 2020-09-23 17:04
Yep that makes sense. Changing it to 2.0.0 fails because it can't locate the pom file at `https://aws-glue-etl-artifacts.s3.amazonaws.com/release/com/amazonaws/AWSGlueETL/2.0.0/AWSGlueETL-2.0.0.pom` (among other places). I'm not savvy enough to figure out how to navigate that, but I'll see what I can do

**Comment by raginjason** [comment] 2020-09-23 17:07
Sadly, I found this: https://forums.aws.amazon.com/thread.jspa?messageID=951854 suggesting I am not alone in locating the Glue 2.0 artifacts

**Comment by jhole89** [comment] 2020-09-23 18:22
Yes, unfortunately for now I can't support Glue 2.0.0 until AWS decides to publish the jar - the internal AWS Glue team is not the most transparent in their releases so I can't say when this will be. For now I recommend using Glue 1.0.

The `myArg` is just an example of passing command line params into your job if you dont want to hard code something (e.g. an s3 bucket), these can be added/removed/changed in the BaseETLScript.

**Comment by jhole89** [comment] 2020-10-24 00:43
Marking as `wontfix` until Jar is available (but leaving issue open so I don't forget about it)

**Comment by raginjason** [comment] 2020-10-26 22:28
Understood. As an aside, I have an open support case with AWS regarding this. I'll let you know what, if anything, comes of it

**Comment by raginjason** [comment] 2020-11-09 22:49
Paraphrasing from the response AWS support gave me: apparently Glue 1.0 used the YARN resource manager, but Glue 2.0 uses an AWS proprietary resource manager. This changed the way Scala classes are loaded. A side effect of this is that methods marked private/protected will not be visible to Glue's resource manager as they belong to a different package.

The fix is simple; just remove the protected keyword. I tested this on Glue 1.0 and Glue 2.0 earlier today and will submit a PR shortly

**Comment by raginjason** [comment] 2020-11-09 23:00
See PR #4 for fix

**Closed as completed** 2021-01-04 17:05 UTC
Labels: bug, question, wontfix
